#!/usr/bin/env bash

set -e

# Ensure $HOME exists
if [ -z "$HOME" ]; then
	echo "❌ HOME variable not set!"
	exit 1
fi

# Definitions
METHOD="SSH"
AUTHOR="$1"
ROOT_DIR="$HOME/GitHub"
AUTHOR_DIR="$ROOT_DIR/$AUTHOR"
GITHUB_DIR="$AUTHOR_DIR/GitHub-Tools"
SHELL_DIR="$AUTHOR_DIR/Shell-Scripts"

# Clone my repos
if [ ! -d "$GITHUB_DIR" ]; then
	bash <(wget -qO- https://github.nikoboi.dev/git/clone) $METHOD $AUTHOR GitHub-Tools
else
	git -C $GITHUB_DIR pull
fi
if [ ! -d "$SHELL_DIR" ]; then
	bash <(wget -qO- https://github.nikoboi.dev/git/clone) $METHOD $AUTHOR Shell-Scripts
else
	git -C $SHELL_DIR pull
fi

wait

# Copy all files to correct directories
echo "ℹ️  Installing scripts..."

echo "alias bcd='source /usr/local/bin/bcd'" >>$HOME/.bash_aliases

# From GitHub-Tools
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/git/setup/automation /usr/local/bin/automation
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/git/setup/workflow /usr/local/bin/workflow
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/git/clone /usr/local/bin/clone
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/git/pull /usr/local/bin/pull
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/git/push /usr/local/bin/push
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/git/status /usr/local/bin/status
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/git/toggle-ssh /usr/local/bin/toggle-ssh

# From Shell-Scripts
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/better-cd /usr/local/bin/bcd
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/better-cp /usr/local/bin/bcp
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/better-mv /usr/local/bin/bmv
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/cat-dir /usr/local/bin/cat-dir
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/find-file /usr/local/bin/find-file
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/find-string /usr/local/bin/find-string
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/linkify /usr/local/bin/linkify
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/repeat /usr/local/bin/repeat

echo "✅ Scripts installed!"

echo "✅ All done!"
