#!/usr/bin/env bash

set -e

# Ensure $HOME exists
if [ -z "$HOME" ]; then
	echo "❌ HOME variable not set!"
	exit 1
fi

# Definitions
METHOD="SSH"
AUTHOR="NikoboiNFTB"
ROOT_DIR="$HOME/GitHub"
AUTHOR_DIR="$ROOT_DIR/$AUTHOR"
GITHUB_DIR="$AUTHOR_DIR/GitHub-Tools"
SHELL_DIR="$AUTHOR_DIR/Shell-Scripts"

# Clone all my repos
bash <(wget -qO- https://github.nikoboi.dev/shell/git/clone) $METHOD $AUTHOR ALL

wait

# Copy all files to correct directories
echo "ℹ️  Installing scripts..."

grep -qxF "alias bcd='source /usr/local/bin/bcd'" "$HOME/.bash_aliases" || echo "alias bcd='source /usr/local/bin/bcd'" >>"$HOME/.bash_aliases"

# From GitHub-Tools
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/shell/git/clone /usr/local/bin/clone
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/shell/git/pull /usr/local/bin/pull
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/shell/git/push /usr/local/bin/push
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/shell/git/status /usr/local/bin/status
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/shell/setup/automation /usr/local/bin/automation
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/shell/setup/workflow /usr/local/bin/workflow
sudo install -m 755 $AUTHOR_DIR/GitHub-Tools/shell/ssh/toggle-ssh /usr/local/bin/toggle-ssh

# From Shell-Scripts
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/random/linkify /usr/local/bin/linkify
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/random/shaify /usr/local/bin/shaify
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/better-cd /usr/local/bin/bcd
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/better-cp /usr/local/bin/bcp
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/better-mv /usr/local/bin/bmv
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/cat-dir /usr/local/bin/cat-dir
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/find-file /usr/local/bin/find-file
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/find-string /usr/local/bin/find-string
sudo install -m 755 $AUTHOR_DIR/Shell-Scripts/utils/repeat /usr/local/bin/repeat

echo "✅ Scripts installed!"

echo "✅ All done!"
