#!/usr/bin/env bash

set -e

# Ensure $HOME exists
if [ -z "$HOME" ]; then
    echo "❌ HOME variable not set!";
    exit 1;
fi

# Definitions
GITHUB_DIR="$HOME/GitHub"
AUTHOR="NikoboiNFTB"
AUTHOR_DIR="$GITHUB_DIR/$AUTHOR"
GIT_REPO="$AUTHOR_DIR/GitHub-Tools/"
PROTON_REPO="$AUTHOR_DIR/Proton-VPN/"
GP8_REPO="$AUTHOR_DIR/Guitar-Pro-On-Linux/"
IO_REPO="$AUTHOR_DIR/nikoboinftb.github.io/"

# Copy
if [ "$(id -u)" -eq 0 ]; then
    cp "$GIT_REPO/shell/git/setup/automation" "/usr/bin/git-automation"
    cp "$GIT_REPO/shell/git/setup/workflow" "/usr/bin/git-workflow"
else
    # GitHub-Tools/git/
    cp "$GIT_REPO/shell/git/setup/automation" "$IO_REPO/shell/git/setup/automation"
    cp "$GIT_REPO/shell/git/setup/gh" "$IO_REPO/shell/git/setup/gh"
    cp "$GIT_REPO/shell/git/setup/git" "$IO_REPO/shell/git/setup/git"
    cp "$GIT_REPO/shell/git/setup/automation" "$IO_REPO/shell/git/setup/automation"

    # GP8
    cp "$GP8_REPO/install" "$IO_REPO/shell/gp8/install"

    # Proton
    cp "$PROTON_REPO/install-icons" "$IO_REPO/shell/proton/install-icons"
    cp "$PROTON_REPO/setup" "$IO_REPO/shell/proton/setup"

    # GitHub-Tools/utils/
    cp "$GIT_REPO/shell/utils/compare" "$IO_REPO/shell/utils/compare"
    cp "$GIT_REPO/shell/utils/find-file" "$IO_REPO/shell/utils/find-file"
    cp "$GIT_REPO/shell/utils/find-.-filter-files" "$IO_REPO/shell/utils/find-.-filter-files"
    cp "$GIT_REPO/shell/utils/find-string" "$IO_REPO/shell/utils/find-string"
    cp "$GIT_REPO/shell/utils/sort" "$IO_REPO/shell/utils/sort"
    cp "$GIT_REPO/shell/utils/SORTME.txt" "$IO_REPO/shell/utils/SORTME.txt"
fi
